package com.example.core.designsystem.theme

import androidx.compose.ui.graphics.Color

/**
 * Палитра редизайна 2026. Принцип (см. SCREEN_REQUIREMENTS.md §2): нейтральная база
 * (off-white в light / графит в dark) + ОДИН уверенный акцент — продуктовый синий.
 * Фирменный сине-белый эволюционирует, а не ломается: акцент остаётся узнаваемо синим.
 */

// --- Light: нейтральный off-white + один синий акцент ---
val LightPrimary = Color(0xFF2F6BED)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFDBE6FF)
val LightOnPrimaryContainer = Color(0xFF0A2960)
val LightSecondary = Color(0xFF4B6391)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFDDE6F6)
val LightOnSecondaryContainer = Color(0xFF142A4D)
val LightTertiary = Color(0xFF2F6BED)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFDBE6FF)
val LightOnTertiaryContainer = Color(0xFF0A2960)
val LightBackground = Color(0xFFF6F7F9)
val LightOnBackground = Color(0xFF121620)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF121620)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF3F5F8)
val LightSurfaceContainer = Color(0xFFEEF1F5)
val LightSurfaceContainerHigh = Color(0xFFE7EBF1)
val LightSurfaceContainerHighest = Color(0xFFE1E6ED)
val LightSurfaceVariant = Color(0xFFE9EDF3)
val LightOnSurfaceVariant = Color(0xFF5A6072)
val LightOutline = Color(0xFFBCC2CE)
val LightOutlineVariant = Color(0xFFDDE1E8)
val LightError = Color(0xFFB3261E)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFF9DEDC)
val LightOnErrorContainer = Color(0xFF410E0B)

// --- Dark: нейтральный графит (НЕ инверсия), акцент чуть мягче ---
val DarkPrimary = Color(0xFF9DBBFF)
val DarkOnPrimary = Color(0xFF0A2150)
val DarkPrimaryContainer = Color(0xFF26406F)
val DarkOnPrimaryContainer = Color(0xFFD9E3FF)
val DarkSecondary = Color(0xFFB0C2E6)
val DarkOnSecondary = Color(0xFF1A2E4D)
val DarkSecondaryContainer = Color(0xFF2B3D5B)
val DarkOnSecondaryContainer = Color(0xFFD7E2FA)
val DarkTertiary = Color(0xFF9DBBFF)
val DarkOnTertiary = Color(0xFF0A2150)
val DarkTertiaryContainer = Color(0xFF26406F)
val DarkOnTertiaryContainer = Color(0xFFD9E3FF)
val DarkBackground = Color(0xFF0F1218)
val DarkOnBackground = Color(0xFFE6E9EF)
val DarkSurface = Color(0xFF151922)
val DarkOnSurface = Color(0xFFE6E9EF)
val DarkSurfaceContainerLowest = Color(0xFF0D1016)
val DarkSurfaceContainerLow = Color(0xFF161A23)
val DarkSurfaceContainer = Color(0xFF1B2029)
val DarkSurfaceContainerHigh = Color(0xFF222834)
val DarkSurfaceContainerHighest = Color(0xFF2C323F)
val DarkSurfaceVariant = Color(0xFF272D38)
val DarkOnSurfaceVariant = Color(0xFFA7AEBE)
val DarkOutline = Color(0xFF3C4350)
val DarkOutlineVariant = Color(0xFF2A303B)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690100)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)

// --- Токены статусов (приглушённые) — только для статусов документов и готовности ---
val LightStatusSuccess = Color(0xFF2E8B57)
val LightStatusSuccessContainer = Color(0xFFDCF1E4)
val LightStatusWarning = Color(0xFFB07A12)
val LightStatusWarningContainer = Color(0xFFF6ECD4)
val LightStatusInfo = Color(0xFF2F6BED)
val LightStatusInfoContainer = Color(0xFFDDE9FF)
val LightStatusNeutral = Color(0xFF5A6072)
val LightStatusNeutralContainer = Color(0xFFE9EDF3)

val DarkStatusSuccess = Color(0xFF6FD79E)
val DarkStatusSuccessContainer = Color(0xFF16331F)
val DarkStatusWarning = Color(0xFFE0B257)
val DarkStatusWarningContainer = Color(0xFF362A12)
val DarkStatusInfo = Color(0xFF9DBBFF)
val DarkStatusInfoContainer = Color(0xFF26406F)
val DarkStatusNeutral = Color(0xFFA7AEBE)
val DarkStatusNeutralContainer = Color(0xFF272D38)
